// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZLaP5ncF3l5XYFBZ7MbjZ187J0XDqqQ',
    appId: '1:474084026323:web:7c2b965c12db49076a3126',
    messagingSenderId: '474084026323',
    projectId: 'calendupelogin',
    authDomain: 'calendupelogin.firebaseapp.com',
    storageBucket: 'calendupelogin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDS7HaG6y1hO6BKc0Yj08ofcFykZrmJU',
    appId: '1:474084026323:android:5c882110028a64496a3126',
    messagingSenderId: '474084026323',
    projectId: 'calendupelogin',
    storageBucket: 'calendupelogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2844z-JQ8sb0x_3-i8_U7y1XUIGx068',
    appId: '1:474084026323:ios:abc77da746639b576a3126',
    messagingSenderId: '474084026323',
    projectId: 'calendupelogin',
    storageBucket: 'calendupelogin.firebasestorage.app',
    iosBundleId: 'com.example.calendarioupe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2844z-JQ8sb0x_3-i8_U7y1XUIGx068',
    appId: '1:474084026323:ios:abc77da746639b576a3126',
    messagingSenderId: '474084026323',
    projectId: 'calendupelogin',
    storageBucket: 'calendupelogin.firebasestorage.app',
    iosBundleId: 'com.example.calendarioupe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxZLaP5ncF3l5XYFBZ7MbjZ187J0XDqqQ',
    appId: '1:474084026323:web:6e04a693622039226a3126',
    messagingSenderId: '474084026323',
    projectId: 'calendupelogin',
    authDomain: 'calendupelogin.firebaseapp.com',
    storageBucket: 'calendupelogin.firebasestorage.app',
  );
}
